begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(10);
select ok('mature' = any(enum_range(null::public.content_rating)::text[]), 'mature is a real database rating');
select is((select count(*)::integer from public.prompts where draw_enabled and rating = 'mature'), 31, '31 explicitly rated mature lines');
select is((select count(*)::integer from public.prompts where draw_enabled and rating = 'everyone'), 36, '36 clean host lines');
select is((select count(*)::integer from public.prompts where draw_enabled and rating = 'teen'), 19, '19 spicy lines distinct from mature');
select is((select body from public.prompts where slug = 'timeline-needs-me'), 'The timeline has been quiet. Unfortunately, I have arrived.', 'historical line body is unchanged');
select is((select state::text from public.prompts where slug = 'timeline-needs-me'), 'published', 'retirement preserves published history joins');
select is((select draw_enabled from public.prompts where slug = 'timeline-needs-me'), false, 'retired prompt cannot join new draws');
select is((select draw_enabled from public.energy_modifiers where slug = 'lying-to-police'), false, 'old direction retired without deletion');
do $$ begin perform public.ensure_daily_challenge('2099-01-01'::date, 'classic-v2-test'); end $$;
select is((select p.rating::text from public.daily_challenges d join public.prompts p on p.id = d.prompt_id where d.challenge_date = '2099-01-01' and d.market = 'classic-v2-test'), 'everyone', 'new canonical Daily selects clean content');
create temporary table saved_daily as select * from public.daily_challenges where challenge_date = '2099-01-01' and market = 'classic-v2-test';
update public.prompts set draw_enabled = false where id = (select prompt_id from saved_daily);
update public.energy_modifiers set draw_enabled = false where id = (select energy_modifier_id from saved_daily);
select is((public.ensure_daily_challenge('2099-01-01'::date, 'classic-v2-test')).prompt_id, (select prompt_id from saved_daily), 'existing Daily pairing survives content retirement');
select * from finish();
rollback;
