begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values ('66666666-1000-4000-8000-000000000001','community-claim@example.test','{"user_name":"community_claim"}');
create temporary table community_fixture as select null::uuid id,
 jsonb_build_object('mode','classic','promptId',id,'scoringVersion','community-test','rubricVersion','community-test','rating','everyone') assignment
 from public.prompts where slug='timeline-needs-me';
grant all on community_fixture to service_role;
set local role service_role;
select lives_ok($q$select public.create_group_round(null,repeat('a',64),repeat('b',64),'Community',assignment,now()+interval '1 hour',null,'77777777-1000-4000-8000-000000000001','Host',true,10,true,repeat('c',64)) from community_fixture$q$, 'real service role creates community round');
update community_fixture set id=(select id from public.challenges where group_token_hash=repeat('b',64));
select is((select community_phase from public.challenges where id=(select id from community_fixture)),'submissions','starts accepting submissions');
select public.group_round_action(id,null,lpad(i::text,64,'0'),'join',jsonb_build_object('displayName','Viewer '||i)) from community_fixture cross join generate_series(1,13) i;
select is((select count(*)::int from public.challenge_group_members where challenge_id=(select id from community_fixture)),14,'community exceeds private twelve-person cap');
reset role;
create temporary table community_people as select m.* from public.challenge_group_members m where challenge_id=(select id from community_fixture);
grant select on community_people to service_role;
insert into public.challenge_group_takes(challenge_id,member_id,attempt_key,request_fingerprint,mode,recording_path,audio_mime,audio_hash,duration_ms,scoring_version,expires_at)
select challenge_id,id,'community-take-'||id,'community-test','classic','community-fixture/'||id||'.wav','audio/wav','fixture',1000,'community-test',now()+interval '14 days' from community_people;
set local role service_role;
select throws_ok($q$select public.group_round_action(f.id,null,m.guest_owner_hash,'submit',jsonb_build_object('takeId',t.id)) from community_fixture f join community_people m on m.guest_owner_hash=lpad('1',64,'0') join public.challenge_group_takes t on t.member_id=m.id$q$,'P0001','ROUND_BROADCAST_CONSENT','private consent alone is insufficient');
select public.group_round_action(f.id,null,m.guest_owner_hash,'submit',jsonb_build_object('takeId',t.id,'broadcastConsent',true)) from community_fixture f join community_people m on m.guest_owner_hash in (lpad('1',64,'0'),lpad('2',64,'0')) join public.challenge_group_takes t on t.member_id=m.id;
select is((select count(*)::int from public.challenge_group_takes where challenge_id=(select id from community_fixture) and broadcast_consent_at is not null),2,'consent is attached to exact submitted takes');
select throws_ok($q$select public.group_round_action(id,null,lpad('1',64,'0'),'showcase','{}') from community_fixture$q$,'P0001','ROUND_FORBIDDEN','performer cannot operate host phases');
select lives_ok($q$select public.group_round_action(id,null,repeat('a',64),'select',jsonb_build_object('memberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')))) from community_fixture$q$,'host selects consented entry');
select throws_ok($q$select public.group_round_action(id,null,repeat('a',64),'select',jsonb_build_object('memberId',(select id from community_people where guest_owner_hash=lpad('3',64,'0')))) from community_fixture$q$,'P0001','ROUND_TAKE_INVALID','draft cannot be selected');
-- Claim retains the same member and host identity. No synthetic OAuth result.
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',repeat('a',64),'claim','{}') from community_fixture$q$,'authenticated host claim succeeds');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',repeat('a',64),'claim','{}') from community_fixture$q$,'duplicate claim succeeds');
select is((select count(*)::int from public.challenge_group_members where challenge_id=(select id from community_fixture)),14,'claim does not duplicate membership');
select throws_ok($q$select public.group_round_action(id,null,repeat('a',64),'join','{"displayName":"Signed out"}') from community_fixture$q$,'P0001','ROUND_SIGN_IN_REQUIRED','claimed guest must sign back in');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'close','{}') from community_fixture$q$,'account retains host authority without guest cookie');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'close','{}') from community_fixture$q$,'close retry is idempotent');
select is((select community_phase from public.challenges where id=(select id from community_fixture)),'review','closing does not expose queue to audience');
select lives_ok($q$select public.group_round_action(id,null,repeat('d',64),'join','{"displayName":"Late audience"}') from community_fixture$q$,'audience can join after recording closes');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'showcase','{}') from community_fixture$q$,'host starts showcase');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'display',jsonb_build_object('memberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')),'command','play','revision',0)) from community_fixture$q$,'host selects display playback');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'display',jsonb_build_object('memberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')),'command','replay','revision',0)) from community_fixture$q$,'stale display retry acknowledged without replaying');
select is((select display_revision from public.challenges where id=(select id from community_fixture)),1,'duplicate command changes no display revision');
select throws_ok($q$select public.group_round_action(id,null,repeat('d',64),'vote',jsonb_build_object('targetMemberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')))) from community_fixture$q$,'55000','ROUND_VOTE_INVALID','votes cannot arrive before voting starts');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'start-voting','{}') from community_fixture$q$,'host opens voting');
select throws_ok($q$select public.group_round_action(id,null,repeat('d',64),'vote',jsonb_build_object('targetMemberId',(select id from community_people where guest_owner_hash=lpad('2',64,'0')))) from community_fixture$q$,'22023','ROUND_VOTE_INVALID','unselected submission is not on ballot');
select throws_ok($q$select public.group_round_action(id,null,lpad('1',64,'0'),'vote',jsonb_build_object('targetMemberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')))) from community_fixture$q$,'22023','ROUND_VOTE_INVALID','performer cannot self-vote');
select lives_ok($q$select public.group_round_action(id,null,repeat('d',64),'vote',jsonb_build_object('targetMemberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')))) from community_fixture$q$,'audience votes for selected entry');
select lives_ok($q$select public.group_round_action(id,null,repeat('d',64),'vote',jsonb_build_object('targetMemberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')))) from community_fixture$q$,'vote retry is idempotent');
select is((select count(*)::int from public.challenge_group_votes where challenge_id=(select id from community_fixture)),1,'one effective vote per identity');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'end-voting','{}') from community_fixture$q$,'host closes voting');
select throws_ok($q$select public.group_round_action(id,null,repeat('d',64),'vote',jsonb_build_object('targetMemberId',(select id from community_people where guest_owner_hash=lpad('1',64,'0')))) from community_fixture$q$,'55000','ROUND_VOTE_INVALID','late duplicate vote rejected server-side');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'end-voting','{}') from community_fixture$q$,'ending twice is harmless');
select lives_ok($q$select public.create_group_round('66666666-1000-4000-8000-000000000001',null,repeat('e',64),'Next',assignment,now()+interval '1 hour',id,'77777777-1000-4000-8000-000000000002','Host',true,10,true,repeat('f',64)) from community_fixture$q$,'host creates linked next community round');
select ok((select community_next_id is not null from public.challenges where id=(select id from community_fixture)),'previous round advertises next round');
select throws_ok($q$select public.create_group_round('66666666-1000-4000-8000-000000000001',null,repeat('9',64),'Duplicate next',assignment,now()+interval '1 hour',id,'77777777-1000-4000-8000-000000000003','Host',true,10,true,repeat('8',64)) from community_fixture$q$,'P0001','ROUND_NEXT_EXISTS','concurrent next-round requests cannot split the community');
select lives_ok($q$select public.group_round_action(id,'66666666-1000-4000-8000-000000000001',null,'revoke-display','{}') from community_fixture$q$,'host revokes display separately from invitations');
select ok((select display_revoked_at is not null and group_invite_revoked_at is null from public.challenges where id=(select id from community_fixture)),'display revocation preserves member invitation');
reset role;
select lives_ok($q$delete from public.challenge_group_takes where member_id=(select id from community_people where guest_owner_hash=lpad('1',64,'0'))$q$,'cleanup removes recording without breaking round references');
select ok((select submitted_take_id is null from public.challenge_group_members where id=(select id from community_people where guest_owner_hash=lpad('1',64,'0'))),'deleted recording has no fallback');
select lives_ok($q$delete from auth.users where id='66666666-1000-4000-8000-000000000001'$q$,'host account deletion respects display foreign key');
select ok((select group_host_member_id is null from public.challenges where id=(select id from community_fixture)),'host deletion removes privileged identity');
select * from finish();
rollback;
