"use client";

import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Copy, Heart, Link2, LoaderCircle, LockKeyhole, Mic, Play, RefreshCw, ShieldCheck, Trophy, Users } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { ContentControl } from "@/components/content/content-control";
import { useApp } from "@/components/providers/app-provider";
import { VideoExport } from "@/components/exports/video-export";
import type { GroupMember, GroupPerformance, GroupRound } from "@/lib/groups/types";
import { isRatingAllowed } from "@/data/content";
import { cn } from "@/lib/utils";
import { RoundApiError, roundDate } from "./round-api";
import { AssignmentCard, GroupPlayback, RoundUnavailable, ScoreDetails, performanceScore } from "./round-shared";
import { CommunityPanel } from "./community-panel";
import { useRound } from "./use-round";

export function RoundRoom({ token, pendingAttemptId, pendingTakeId }: { token: string; pendingAttemptId?: string; pendingTakeId?: string }) {
  const router = useRouter();
  const { authenticated, profile, contentRating, updatePreferences } = useApp();
  const { round, loading, error, busy, refresh, act } = useRound(token);
  const [displayName, setDisplayName] = useState("");
  const [selectedTakeId, setSelectedTakeId] = useState(pendingAttemptId ?? pendingTakeId ?? "");
  const [consent, setConsent] = useState(false);
  const [notice, setNotice] = useState("");
  const [confirm, setConfirm] = useState<"close" | "revoke" | null>(null);
  const [showInvite, setShowInvite] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const returnPath = `/rounds/${encodeURIComponent(token)}`;

  useEffect(() => { if (authenticated) setDisplayName((current) => current || profile.displayName); }, [authenticated, profile.displayName]);
  useEffect(() => { setSelectedTakeId(pendingAttemptId ?? pendingTakeId ?? ""); setConsent(false); }, [token, pendingAttemptId, pendingTakeId]);
  useEffect(() => { setShowInvite(false); setConfirm(null); setNotice(""); }, [token]);

  if (round && !isRatingAllowed(round.assignment.rating, contentRating)) return <RoundUnavailable loading={false} error={new RoundApiError("Choose the appropriate content setting before opening this assignment or its performances.", 403, "CONTENT_OPT_IN_REQUIRED")} retry={() => void refresh()} />;
  if (!round || error?.code === "CONTENT_OPT_IN_REQUIRED") return <RoundUnavailable loading={loading} error={error} retry={() => void refresh()} />;
  const own = round.members.find((member) => member.isYou);
  const candidate = selectedTakeId ? round.yourTakes.find((take) => takeIdentity(take) === selectedTakeId) ?? (takeIdentity(own?.performance) === selectedTakeId ? own?.performance ?? null : null) : own?.performance ?? round.yourTakes[0] ?? null;
  const currentSubmission = Boolean(candidate && own?.submitted && takeIdentity(own.performance) === takeIdentity(candidate));
  const pendingMissing = Boolean(selectedTakeId && !candidate && round.viewerMemberId);
  const invitationUrl = typeof window === "undefined" ? returnPath : new URL(returnPath, window.location.origin).href;
  const recordPath = `${returnPath}/record`;
  const rematchPath = `/rounds?from=${encodeURIComponent(token)}${round.community ? "&community=1" : ""}`;

  async function copyInvite() {
    setShowInvite(true);
    try { await navigator.clipboard.writeText(invitationUrl); setNotice("Invitation copied. Send it to your friends."); }
    catch { setNotice("Select and copy the invitation below."); window.setTimeout(() => inputRef.current?.select(), 0); }
  }
  async function submit() {
    if (!candidate || !consent) return;
    const next = await act("submit", { ...(candidate.mode === "switch" ? { switchAttemptId: candidate.switchAttempt?.id ?? candidate.takeId } : candidate.mode === "say-it-back" ? { sayAttemptId: candidate.sayAttempt?.id ?? candidate.takeId } : { takeId: candidate.takeId }), consent: true, ...(round?.community ? { broadcastConsent: true } : {}) });
    if (next) {
      setConsent(false); setNotice(round?.community ? "Submitted for host review. You can replace it until submissions close." : own?.submitted ? "Your submitted performance has been replaced. Your friends will see this take at reveal." : "You’re in. Your performance stays hidden from the group until reveal.");
      setSelectedTakeId(takeIdentity(candidate));
      router.replace(returnPath, { scroll: false });
    }
  }

  return <main className="min-h-screen px-4 pb-28 pt-28 sm:px-6 sm:pt-32"><div className="mx-auto max-w-6xl">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/rounds" className="button-ghost -ml-3 px-3"><ArrowLeft className="size-4" />Friend rounds</Link><div className="flex items-center gap-2"><span className={cn("rounded-full border px-3 py-1.5 text-[10px] font-bold uppercase tracking-wide", round.state === "open" ? "border-electric/30 bg-electric/10 text-electric" : round.state === "revealed" ? "border-hot/30 bg-hot/10 text-hot" : "border-white/20 text-white/55")}>{round.state === "open" ? "Recording open" : round.state === "revealed" ? "Now showing" : "Replay ended"}</span><button type="button" onClick={() => void refresh(true)} disabled={Boolean(busy)} className="icon-button" aria-label="Refresh round"><RefreshCw className="size-4" /></button></div></div>
    <header className="mb-7 grid gap-5 border-b border-white/15 pb-7 lg:grid-cols-[1.3fr_1fr] lg:items-end"><div className="min-w-0"><p className="mono-label mb-3 flex items-center gap-2 text-hot"><Users className="size-4" />{round.community?.participantCount ?? round.members.length}/{round.maxMembers} {round.community ? "viewers" : "friends"} · {round.assignment.mode === "switch" ? "Switch · Beta" : round.assignment.mode === "say-it-back" ? "Say It Back" : "Classic"}</p><h1 className="display-type break-words text-[clamp(2.8rem,7vw,5.5rem)] leading-[.95]">{round.name}</h1></div><p className="max-w-lg text-sm leading-7 text-white/65">{round.community ? "Record your interpretation, or join just to watch and vote. The host privately previews submissions and selects the show." : round.state === "open" ? "Your friends, their own interpretations. Rehearse privately, submit one take, and come back for everyone’s performances." : round.state === "revealed" ? "The microphones are down. Watch every take, compare the performances, and give your favorite the audience vote." : "This round’s 7-day replay window has ended. Start another one to give the group a fresh assignment."}</p></header>
    {round.previousRoundUrl && <Link href={round.previousRoundUrl} className="mb-5 inline-flex min-h-10 items-center gap-2 text-xs font-bold text-electric underline"><ArrowLeft className="size-3.5" />Revisit the previous round</Link>}
    {error && <p role="alert" className="mb-5 rounded-xl border border-orange-300/25 bg-orange-300/5 p-4 text-sm leading-6 text-orange-200">{error.message} <button type="button" onClick={() => void refresh(true)} className="underline">Refresh round</button></p>}
    {notice && <p role="status" className="mb-5 flex items-start gap-2 rounded-xl border border-electric/25 bg-electric/5 p-4 text-sm leading-6 text-electric"><CheckCircle2 className="mt-1 size-4 shrink-0" />{notice}</p>}

    {round.state === "expired" ? <section className="rounded-2xl border border-white/15 bg-surface p-6 sm:p-8"><Clock3 className="size-8 text-hot" /><h2 className="mt-4 text-2xl font-bold">Good performances deserve an encore.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/65">Group replay ended {roundDate(round.replayUntil)}. The assignment and previous result record stay separate from your next round; expired private recordings cannot be replayed here.</p><Link href={round.viewerMemberId ? rematchPath : "/rounds"} className="button-primary mt-6">Start another round<ArrowRight className="size-4" /></Link></section> : <>
      {!round.viewerMemberId && <section className="mb-6 overflow-hidden rounded-2xl bg-paper p-5 text-ink sm:p-7"><div className="grid gap-6 md:grid-cols-[1fr_1fr]"><div><p className="mono-label text-ink/55">Your mic is invited</p><h2 className="mt-2 text-2xl font-bold">{round.canJoin ? "What should we call you?" : round.state === "revealed" ? "This round has already revealed." : round.inviteRevoked ? "New joins have been closed." : "This group is full."}</h2><p className="mt-3 text-sm leading-6 text-ink/65">{round.canJoin ? "Join with a display name. No camera or account required. Already submitted? Return in the original browser or sign in to your linked account. A new guest place cannot recover a missing cookie or previous take." : "Existing members can return using their original browser or linked account. Ask your friend for the next-round link."}</p></div>{round.canJoin ? <form onSubmit={(event) => { event.preventDefault(); void act("join", { displayName: displayName.trim() }); }}><label htmlFor="join-name" className="text-xs font-bold">Your display name</label><input id="join-name" required minLength={1} maxLength={32} autoComplete="nickname" value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="What your friends call you" disabled={Boolean(busy)} className="mt-2 min-h-12 w-full rounded-xl border border-ink/25 bg-transparent px-3 text-sm placeholder:text-ink/45" /><button type="submit" disabled={Boolean(busy) || !displayName.trim()} className="button-primary mt-3 w-full">{busy === "join" ? <LoaderCircle className="size-4 animate-spin" /> : <Mic className="size-4" />}Join the round</button><p className="mt-3 text-[11px] leading-5 text-ink/60">{round.community ? "Your selected performance and display name may appear on stream only after explicit submission consent. Watching and voting never need microphone access." : "Your name is visible to the group. Performances are shared only when you submit them; the group sees them after reveal."}</p></form> : <div className="self-center"><Link href={`/login?next=${encodeURIComponent(returnPath)}`} className="button-secondary border-ink/25 text-ink">Sign in to return</Link><Link href="/rounds" className="mt-3 block min-h-10 py-2 text-sm font-bold underline">Create your own round</Link></div>}</div></section>}

      {round.community && <CommunityPanel round={round} busy={busy} act={act} refresh={() => refresh(true)} />}
      {!round.community && round.state === "revealed" && round.viewerMemberId ? <RoundShowcase round={round} busy={busy} refresh={() => refresh(true)} vote={(memberId) => act("vote", { memberId }).then((result) => { if (result) setNotice("Audience vote saved. You can change it during the replay window."); })} /> : <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(290px,1fr)]">
        <div className="min-w-0 space-y-5"><AssignmentCard assignment={round.assignment} />
          {round.viewerMemberId && round.state === "open" && <section id="your-take" className="scroll-mt-24 rounded-2xl border border-hot/25 bg-hot/[0.04] p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="mono-label text-hot">Your private corner</p><h2 className="mt-2 text-xl font-bold">{own?.submitted ? "Your take is in. Still time for an encore." : candidate ? "Happy with this one?" : "Give them a performance."}</h2></div>{own?.submitted && <span className="flex items-center gap-1.5 text-xs font-bold text-electric"><CheckCircle2 className="size-4" />Submitted</span>}</div>
            <p className="mt-3 text-sm leading-6 text-white/65">{own?.submitted ? "You can replace your submitted take until the round closes. The previous submission stays in place until a replacement succeeds." : "Record and replay privately, then choose exactly one performance to share with this group."}</p>
            {pendingMissing && <p role="alert" className="mt-4 rounded-xl border border-orange-300/25 p-3 text-xs leading-6 text-orange-200">That take is not available to this browser in this round. Return using the browser that recorded it, or make a new take. No different take has been selected for you.</p>}
            {candidate && <div className="mt-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-bold text-white/70">{currentSubmission ? "Your current submission" : "Private preview · not submitted"}</p><p className="text-[10px] text-white/50">{candidate.scoreGroup === "unscored" ? "No score" : candidate.scoreGroup === "words-only" ? "Words-only match" : candidate.scoreGroup === "switch-beta" ? "Switch beta · casual score" : "Scored take"}</p></div><GroupPlayback performance={candidate} assignment={round.assignment} label="Your take" refresh={() => refresh(true)} /><ScoreDetails performance={candidate} /><VideoExport key={takeIdentity(candidate)} mode={candidate.mode} attemptId={candidate.switchAttempt?.id ?? candidate.sayAttempt?.id ?? candidate.takeId} hasScore={performanceScore(candidate) != null} reopenPath={returnPath} compact />
              {!currentSubmission && <div className="border-t border-white/15 pt-4">{!candidate.canSubmit ? <p role="alert" className="text-sm leading-6 text-orange-200">This recording is not eligible to share. Choose another private take or record again.</p> : <><label className="flex cursor-pointer items-start gap-3 text-xs leading-6 text-white/75"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-1 size-4 shrink-0 accent-acid" />{round.community ? "I allow the host to privately preview and showcase/broadcast this exact recording, including camera footage when recorded, and my display name. The stream may be recorded externally; deleting this in-app recording cannot retract external broadcasts." : "I agree to share this exact recording, including camera footage when recorded, with members of this round after reveal. Anyone with the invite can join while it is open."}{candidate.sharingStatus === "unreviewed" ? " This take has not been automatically reviewed; keep it within this round’s content setting." : ""}</label><button type="button" disabled={!consent || Boolean(busy)} onClick={() => void submit()} className="button-primary mt-4 w-full">{busy === "submit" ? <LoaderCircle className="size-4 animate-spin" /> : <CheckCircle2 className="size-4" />}{own?.submitted ? "Replace my submitted performance" : "Submit this performance"}</button></>}</div>}
            </div>}
            {round.yourTakes.length > 1 && <div className="mt-5"><label htmlFor="private-takes" className="text-xs font-bold text-white/65">Choose a different private take</label><select id="private-takes" value={takeIdentity(candidate)} onChange={(event) => { setSelectedTakeId(event.target.value); setConsent(false); }} className="mt-2 min-h-12 w-full rounded-xl border border-white/20 bg-ink px-3 text-sm"><option value="" disabled>Choose a take</option>{round.yourTakes.map((take, index) => <option key={take.takeId} value={takeIdentity(take)}>Take {round.yourTakes.length - index} · {(take.durationMs / 1000).toFixed(1)} sec · {performanceScore(take) == null ? "unscored" : `${Math.round(performanceScore(take)!)} ${take.scoreGroup === "words-only" ? "words only" : "points"}`}{takeIdentity(own?.performance) === takeIdentity(take) ? " · submitted" : ""}</option>)}</select></div>}
            <Link href={recordPath} className={cn("mt-5 w-full", candidate ? "button-secondary" : "button-primary")}><Mic className="size-4" />{candidate || own?.submitted ? "Record another take" : "Record my performance"}<ArrowRight className="size-4" /></Link>
            {(candidate?.mode === "say-it-back" || candidate?.mode === "switch") && candidate.scoreGroup === "unscored" && <Link href={`${recordPath}?attempt=${encodeURIComponent(candidate.switchAttempt?.id ?? candidate.sayAttempt?.id ?? candidate.takeId)}`} className="mt-3 block min-h-10 py-2 text-center text-xs font-bold text-white/65 underline">Get feedback for this take · optional</Link>}
            <p className="mt-3 flex items-start gap-2 text-[11px] leading-5 text-white/50"><LockKeyhole className="mt-0.5 size-3.5 shrink-0" />Only your chosen submission will be revealed. Recording and sharing are free; an optional score uses your daily scored-play allowance.</p>
          </section>}
        </div>
        <aside className="min-w-0 space-y-5">{!round.community && <RoundProgress round={round} />}
          {!round.community && round.state === "open" && round.viewerMemberId && !round.inviteRevoked && <section className="rounded-2xl border border-white/15 p-5"><h2 className="flex items-center gap-2 text-sm font-bold"><Link2 className="size-4 text-hot" />Bring the group chat.</h2><p className="mt-2 text-xs leading-6 text-white/60">Anyone with the invitation can join until the round closes or its 12 places fill. Share it with people you know.</p><button type="button" onClick={() => void copyInvite()} className="button-secondary mt-4 w-full"><Copy className="size-4" />Copy invitation link</button>{showInvite && <input ref={inputRef} aria-label="Round invitation link" readOnly value={invitationUrl} onFocus={(event) => event.target.select()} className="mt-3 min-h-11 w-full rounded-lg border border-white/20 bg-ink px-3 text-xs" />}</section>}
          {!round.community && round.isHost && round.state === "open" && <section className="rounded-2xl border border-white/15 p-5"><p className="mono-label text-white/50">Host controls</p><h2 className="mt-2 text-base font-bold">Ready for the premiere?</h2><p className="mt-2 text-xs leading-6 text-white/60">Close early to reveal submitted takes. The automatic deadline still works if you’re away.</p><button type="button" disabled={Boolean(busy)} onClick={() => setConfirm("close")} className="button-secondary mt-4 w-full"><Play className="size-4" />Close & reveal now</button>{!round.inviteRevoked && <button type="button" disabled={Boolean(busy)} onClick={() => setConfirm("revoke")} className="button-ghost mt-2 w-full text-xs">Stop new joins</button>}{confirm && <div className="mt-4 rounded-xl border border-acid/30 bg-acid/5 p-4"><p className="text-xs leading-6 text-white/75">{confirm === "close" ? `Reveal ${round.submittedCount} ${round.submittedCount === 1 ? "performance" : "performances"} now? This ends recording and replacement for everyone. ${round.submittedCount === 0 ? "No performances have been submitted yet." : ""}` : "Stop anyone new from joining with this invitation? Current members can still record, submit, and return."}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={Boolean(busy)} onClick={() => void act(confirm).then((result) => { if (result) { setConfirm(null); setNotice(confirm === "revoke" ? "New joins are closed. Existing members still have access." : "The round is revealed. Time to watch the performances."); } })} className="button-primary min-h-10 px-3 text-xs">{busy ? <LoaderCircle className="size-4 animate-spin" /> : <Check className="size-4" />}{confirm === "close" ? "Reveal performances" : "Stop new joins"}</button><button type="button" disabled={Boolean(busy)} onClick={() => setConfirm(null)} className="button-ghost min-h-10 px-3 text-xs">Keep it open</button></div></div>}</section>}
        </aside>
      </div>}

      {round.viewerMemberId && <div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-white/15 p-5"><p className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="size-4 text-electric" />{round.isGuest ? "Keep your place in the group." : "Your group access"}</p>{round.isGuest ? <><p className="mt-2 text-xs leading-6 text-white/60">Guest access belongs to this browser’s cookies. Clearing them or switching devices can lose your place. Sign in on this browser to retain your membership{round.isHost ? " and host controls" : ""} across devices.</p><Link href={`/login?next=${encodeURIComponent(returnPath)}`} className="button-secondary mt-4">Sign in & keep my access<ArrowRight className="size-4" /></Link></> : round.canClaim ? <><p className="mt-2 text-xs leading-6 text-white/60">You’re signed in. Attach this browser’s guest membership to your account to return from another device.</p><button type="button" disabled={Boolean(busy)} onClick={() => void act("claim").then((result) => { if (result) setNotice("This round is now linked to your account."); })} className="button-secondary mt-4">Keep this round in my account</button></> : <p className="mt-2 text-xs leading-6 text-white/60">Return with this link while signed in to the same account. Group replays remain available until {roundDate(round.replayUntil)}.</p>}<p className="mt-3 text-[11px] leading-5 text-white/50">Casual friend rounds use one place per participant. A display name is not a verified identity.</p></section>
        {!round.community && <section className={cn("rounded-xl border p-5", round.state === "revealed" ? "border-hot/35 bg-hot/10" : "border-white/15")}><p className="mono-label text-hot">The next scene is yours</p><h2 className="mt-2 text-xl font-bold">Same friends. Fresh material.</h2><p className="mt-2 text-xs leading-6 text-white/65">Choose another scene, keep this assignment, or switch game modes. Share a new link; this round’s results stay here.</p><Link href={rematchPath} className={cn("mt-4", round.state === "revealed" ? "button-primary" : "button-secondary")}><RefreshCw className="size-4" />Play again<ArrowRight className="size-4" /></Link></section>}</div>}
    </>}
    <div className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t border-white/15 pt-5"><ContentControl compact allowMature={false} value={contentRating === "mature" ? "teen" : contentRating} onChange={(rating) => updatePreferences({ contentRating: rating })} /><p className="max-w-md text-[11px] leading-5 text-white/45">{round.state === "open" ? "Drafts stay private. " : ""}Group replay lasts 7 days after submissions close. Private drafts are never shown to the group.</p></div>
  </div></main>;
}

function RoundProgress({ round }: { round: GroupRound }) {
  return <section className="rounded-2xl border border-white/15 bg-surface p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-bold">The cast</h2><p className="text-xs font-bold text-electric">{round.submittedCount}/{round.members.length} submitted</p></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-electric transition-[width]" style={{ width: `${round.members.length ? round.submittedCount / round.members.length * 100 : 0}%` }} /></div><ul className="mt-4 space-y-3">{round.members.map((member) => <li key={member.id} className="flex items-center gap-3"><span className={cn("grid size-9 shrink-0 place-items-center rounded-full text-xs font-bold", member.submitted ? "bg-electric/15 text-electric" : "bg-white/5 text-white/60")}>{member.submitted ? <Check className="size-4" /> : member.displayName.slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block break-words text-sm font-bold">{member.displayName}{member.isYou && <span className="font-normal text-white/50"> · you</span>}</span><span className="mt-0.5 block text-[10px] text-white/50">{member.isHost ? "Host · " : ""}{member.submitted ? "Ready for reveal" : "Taking their time"}</span></span>{member.submitted ? <LockKeyhole className="size-3.5 text-electric/60" /> : <Clock3 className="size-3.5 text-white/30" />}</li>)}</ul><div className="mt-5 border-t border-white/15 pt-4"><p className="flex items-start gap-2 text-xs leading-6 text-white/75"><Clock3 className="mt-1 size-4 shrink-0 text-hot" /><span>{round.state === "open" ? "Automatic reveal" : "Revealed"}<strong className="block font-bold">{roundDate(round.closedAt ?? round.closesAt)}</strong></span></p><p className="mt-3 text-[11px] leading-6 text-white/55">{round.state === "open" ? "The host can reveal sooner. Everyone sees the chosen performances together after closure. This page checks progress every 15 seconds." : "Recording has closed. Existing members can watch the submitted performances."}</p>{round.inviteRevoked && <p className="mt-2 text-xs font-bold text-hot">New joins are closed.</p>}</div></section>;
}

function RoundShowcase({ round, busy, refresh, vote }: { round: GroupRound; busy: string; refresh: () => Promise<void>; vote: (memberId: string) => Promise<void> }) {
  const performers = round.members.filter((member) => member.performance);
  const [selected, setSelected] = useState("");
  const member = performers.find((item) => item.id === selected) ?? performers[0];
  const mainGroup = round.assignment.mode === "switch" ? "switch-beta" : round.assignment.mode === "classic" ? "classic" : "full-match";
  const ranked = performers.filter((item) => item.performance?.scoreGroup === mainGroup && performanceScore(item.performance) != null).sort((a, b) => performanceScore(b.performance)! - performanceScore(a.performance)!);
  const wordsOnly = performers.filter((item) => item.performance?.scoreGroup === "words-only").sort((a, b) => performanceScore(b.performance)! - performanceScore(a.performance)!);
  const best = ranked.length ? performanceScore(ranked[0]!.performance) : null;
  const winners = ranked.filter((item) => performanceScore(item.performance) === best);
  const mostVotes = Math.max(0, ...performers.map((item) => item.votes));
  const audience = performers.filter((item) => mostVotes > 0 && item.votes === mostVotes);

  if (!member?.performance) return <section className="rounded-2xl border border-hot/25 bg-hot/5 p-6 text-center sm:p-10"><Mic className="mx-auto size-10 text-hot" /><h2 className="mt-5 text-3xl font-bold">A quiet opening night.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-white/65">No eligible performances were submitted before this round closed. Start another round with a fresh deadline and share its invitation with the group.</p><Link href={`/rounds?from=${encodeURIComponent(round.token)}`} className="button-primary mt-6">Give it another round<ArrowRight className="size-4" /></Link></section>;

  return <section aria-label="Group performances">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="mono-label text-hot">The premiere</p><h2 className="mt-1 text-2xl font-bold">{performers.length === 1 ? "One mic showed up. Make it count." : "Everybody brought something."}</h2></div><p className="text-xs text-white/55">{performers.length} {performers.length === 1 ? "performance" : "performances"} · replay until {roundDate(round.replayUntil)}</p></div>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.65fr)_minmax(285px,1fr)]"><div className="min-w-0 overflow-hidden rounded-2xl border border-hot/30 bg-surface"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/15 p-4 sm:p-5"><div><p className="text-xl font-bold">{member.displayName}{member.isYou && <span className="text-sm font-normal text-white/55"> · you</span>}</p><p className="mt-1 text-xs text-white/55">{round.assignment.mode === "switch" ? round.assignment.challenge.title : round.assignment.mode === "say-it-back" ? round.assignment.clip.title : "Classic · same line, their interpretation"}</p></div><span className="rounded-full bg-hot/10 px-3 py-1.5 text-xs font-bold text-hot">{performers.indexOf(member) + 1} / {performers.length}</span></div>
      <div className="p-3 sm:p-5"><GroupPlayback performance={member.performance} assignment={round.assignment} label={`${member.displayName}’s take`} refresh={refresh} />{member.isYou && <VideoExport key={takeIdentity(member.performance)} mode={member.performance.mode} attemptId={member.performance.switchAttempt?.id ?? member.performance.sayAttempt?.id ?? member.performance.takeId} hasScore={performanceScore(member.performance) != null} reopenPath={round.url} compact />}{round.assignment.mode === "classic" && <p className="mt-5 text-sm font-bold leading-6">“{round.assignment.promptText}”<span className="mt-2 block text-xs font-normal text-white/60">{round.assignment.energy}</span></p>}
        <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-white/65">{member.performance.scoreGroup === "words-only" ? "Words-only match" : member.performance.scoreGroup === "unscored" ? "Replay only" : round.assignment.mode === "switch" ? "Switch beta · casual score" : round.assignment.mode === "classic" ? "Judge score" : "Dialogue match"}</p><p className="mt-1 text-3xl font-bold">{performanceScore(member.performance) == null ? "—" : Math.round(performanceScore(member.performance)!)}{performanceScore(member.performance) != null && <span className="ml-1 text-xs font-normal text-white/50">/100</span>}</p></div><button type="button" disabled={member.isYou || Boolean(busy)} onClick={() => void vote(member.id)} aria-pressed={round.viewerVoteMemberId === member.id} className={cn("button-secondary", round.viewerVoteMemberId === member.id && "border-hot bg-hot/10 text-hot")}><Heart className={cn("size-4", round.viewerVoteMemberId === member.id && "fill-current")} />{member.isYou ? "Your performance" : round.viewerVoteMemberId === member.id ? "Your funniest pick" : "Vote funniest"}</button></div>
        <div className="mt-4 border-t border-white/15 pt-4"><ScoreDetails performance={member.performance} /></div>{member.performance.sharingStatus === "unreviewed" && <p className="mt-3 text-[11px] leading-5 text-white/50">Shared privately by this participant without automated content review.</p>}
        {performers.length > 1 && <div className="mt-5 flex justify-between gap-3 border-t border-white/15 pt-4"><button type="button" onClick={() => setSelected(performers[(performers.indexOf(member) - 1 + performers.length) % performers.length]!.id)} className="button-ghost px-2 text-xs"><ArrowLeft className="size-4" />Previous take</button><button type="button" onClick={() => setSelected(performers[(performers.indexOf(member) + 1) % performers.length]!.id)} className="button-secondary text-xs">Next performance<ArrowRight className="size-4" /></button></div>}
      </div></div>
      <aside className="min-w-0 space-y-4"><section className="rounded-2xl border border-white/15 p-4 sm:p-5"><h3 className="text-sm font-bold">Watch the cast</h3><div className="mt-3 space-y-2">{performers.map((item) => <button type="button" key={item.id} onClick={() => setSelected(item.id)} aria-pressed={member.id === item.id} className={cn("flex min-h-16 w-full items-center gap-3 rounded-xl border p-3 text-left", member.id === item.id ? "border-hot/50 bg-hot/10" : "border-white/10 hover:border-white/30")}><span className={cn("grid size-9 shrink-0 place-items-center rounded-full", member.id === item.id ? "bg-hot text-ink" : "bg-white/5 text-white/60")}><Play className="size-4" /></span><span className="min-w-0 flex-1"><span className="block break-words text-sm font-bold">{item.displayName}{item.isYou ? " · you" : ""}</span><span className="mt-1 flex items-center gap-1 text-[10px] text-white/55">{item.votes > 0 && <><Heart className="size-3" />{item.votes} {item.votes === 1 ? "vote" : "votes"} · </>}{item.performance?.scoreGroup === "words-only" ? "Words-only" : item.performance?.scoreGroup === "unscored" ? "Replay only" : `${Math.round(performanceScore(item.performance)!)} points`}</span></span>{round.viewerVoteMemberId === item.id && <Heart className="size-4 shrink-0 fill-hot text-hot" />}</button>)}</div>{round.members.length > performers.length && <p className="mt-3 text-[11px] leading-6 text-white/50">{round.members.length - performers.length} {round.members.length - performers.length === 1 ? "friend did" : "friends did"} not submit a playable performance before closure.</p>}</section>
      <section className="rounded-2xl border border-hot/25 bg-hot/5 p-5"><p className="mono-label flex items-center gap-2 text-hot"><Heart className="size-4" />Audience choice</p><h3 className="mt-3 text-lg font-bold">{audience.length ? audience.length === 1 ? audience[0]!.displayName : "An audience tie." : "Who made you laugh?"}</h3><p className="mt-2 text-xs leading-6 text-white/65">{audience.length ? `${audience.length > 1 ? audience.map((item) => item.displayName).join(", ") + " · " : ""}${mostVotes} ${mostVotes === 1 ? "vote" : "votes"}. ` : ""}One vote per participant. No self-votes. You can change your pick until replay ends.</p><p className="mt-3 text-[11px] leading-5 text-white/50">A separate audience favorite; it does not change the matching or judge winner.{performers.length === 1 ? " Another participant can vote for this take; the performer cannot vote for themselves." : ""}</p></section>
      </aside></div>
    <section className="mt-5 rounded-2xl border border-white/15 p-5 sm:p-6" aria-label="Comparable results"><p className="mono-label flex items-center gap-2 text-electric"><Trophy className="size-4" />{round.assignment.mode === "switch" ? "Switch beta · casual comparison" : round.assignment.mode === "classic" ? "The judge’s comparison" : "Matching comparison"}</p><h3 className="mt-3 text-xl font-bold">{!winners.length ? "The show comes first." : winners.length > 1 ? `A ${winners.length}-way tie at ${Math.round(best!)}.` : `${winners[0]!.displayName} ${ranked.length === 1 ? "posted" : "leads with"} ${Math.round(best!)}.`}</h3><p className="mt-2 text-xs leading-6 text-white/60">{!ranked.length ? "No compatible full scores are available. Watch the takes and choose your audience favorite." : ranked.length === 1 ? "Only one comparable score is available; there is no head-to-head score winner yet." : winners.length > 1 ? `${winners.map((item) => item.displayName).join(", ")} share the highest score. Ties stay ties.` : "Same assignment and scoring version. Performances without a compatible score stay in the show."}</p>
      {round.assignment.mode === "switch" && <p className="mt-3 text-xs leading-6 text-white/55">Same phrase, cue timeline, and scoring version. Beta feedback supports a casual comparison; it does not enter ranked leaderboards. Audience choice is separate.</p>}
      {ranked.length > 0 && <Ranking members={ranked} label={round.assignment.mode === "switch" ? "Unranked Switch beta comparison" : round.assignment.mode === "classic" ? "Classic judge results" : "Full words, timing, and rhythm matches"} />}{wordsOnly.length > 0 && <div className="mt-5 border-t border-white/15 pt-4"><p className="text-sm font-bold">Words-only results · separate comparison</p><p className="mt-1 text-xs leading-6 text-white/55">Timing or rhythm was unavailable. These scores cannot outrank full matches.</p><Ranking members={wordsOnly} label="Words-only results" /></div>}
    </section>
  </section>;
}

function Ranking({ members, label }: { members: GroupMember[]; label: string }) {
  return <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs" aria-label={label}><thead className="border-b border-white/15 text-white/50"><tr><th className="py-3 pr-4 font-normal">Place</th><th className="py-3 pr-4 font-normal">Performer</th><th className="py-3 text-right font-normal">Score</th></tr></thead><tbody>{members.map((member) => { const score = performanceScore(member.performance)!; const rank = members.findIndex((item) => performanceScore(item.performance) === score) + 1; return <tr key={member.id} className="border-b border-white/[0.07] last:border-0"><td className="py-3 pr-4 tabular-nums text-white/60">{rank}</td><th className="py-3 pr-4 font-bold">{member.displayName}{member.isYou && <span className="font-normal text-white/50"> · you</span>}</th><td className="py-3 text-right font-bold tabular-nums">{Math.round(score)}</td></tr>; })}</tbody></table></div>;
}

function takeIdentity(take: GroupPerformance | null | undefined) {
  return take?.mode === "switch" ? take.switchAttempt?.id ?? take.takeId : take?.mode === "say-it-back" ? take.sayAttempt?.id ?? take.takeId : take?.takeId ?? "";
}
