"use client";

import { Check, MessageSquare, MonitorUp, Radio, SlidersHorizontal, Users } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

export function StreamSetup() {
  const [chatVote, setChatVote] = useState(true);
  const [clean, setClean] = useState(true);
  const [delay, setDelay] = useState("5");
  return <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="panel-solid p-6 sm:p-8"><p className="mono-label text-electric">Control room</p><h2 className="mt-2 text-3xl font-black tracking-[-0.05em]">Tune the chaos</h2><div className="mt-7 grid gap-3"><Toggle icon={MessageSquare} title="On-screen energy vote" description="Show three choices, then press 1–3 to lock the winner from your stream poll or chat." checked={chatVote} onChange={setChatVote} /><Toggle icon={MonitorUp} title="Clean browser source" description="Hide navigation, favorite, and result controls from the stage view for OBS." checked={clean} onChange={setClean} /><label className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-start gap-3"><SlidersHorizontal className="mt-0.5 size-4 text-hot" /><div><p className="text-sm font-black">Voting window</p><p className="mt-1 text-xs leading-5 text-white/55">Seconds the three choices stay on screen.</p></div></div><select value={delay} onChange={(event) => setDelay(event.target.value)} className="rounded-full border border-white/10 bg-[#111] px-3 py-2 text-xs font-black"><option value="3">3 sec</option><option value="5">5 sec</option><option value="10">10 sec</option></select></label></div><Link href={`/stream/stage?vote=${chatVote ? 1 : 0}&clean=${clean ? 1 : 0}&delay=${delay}`} className="button-primary mt-7 w-full min-h-14"><Radio className="size-5" /> Launch stage</Link><p className="mt-3 text-center text-xs font-bold text-white/55">Opens a stage-ready route. Add it as a browser source or share your screen.</p></section><aside className="grid gap-4"><div className="relative overflow-hidden rounded-[26px] border border-electric/25 bg-electric p-6"><div className="absolute inset-0 grid-fade opacity-30" /><div className="relative"><p className="mono-label">Preview</p><p className="mt-8 text-3xl font-black leading-8 tracking-[-0.05em]">“The Wi-Fi has developed free will.”</p><div className="mt-6 rounded-xl bg-black/20 p-3"><p className="mono-label text-acid">Chat chose</p><p className="mt-1 text-sm font-black">Mission control, but make it personal</p></div><div className="mt-7 flex items-center gap-2"><span className="size-2 animate-pulse rounded-full bg-red-400" /><span className="mono-label">Stage preview</span></div></div></div><div className="panel p-5"><p className="mono-label text-hot">Hotkeys</p>{[["Space", "Start / stop"], ["R", "Reroll prompt"], ["V", "Open vote"], ["1–3", "Lock vote winner"], ["F", "Toggle fullscreen"]].map(([key, action]) => <div key={key} className="flex items-center justify-between border-b border-white/10 py-2.5 last:border-0"><span className="text-xs font-bold text-white/45">{action}</span><kbd className="rounded-md border border-white/15 bg-white/5 px-2 py-1 font-mono text-xs font-black">{key}</kbd></div>)}</div></aside></div>;
}

function Toggle({ icon: Icon, title, description, checked, onChange }: { icon: typeof Users; title: string; description: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <button type="button" onClick={() => onChange(!checked)} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-left"><div className="flex items-start gap-3"><Icon className="mt-0.5 size-4 text-acid" /><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs leading-5 text-white/55">{description}</p></div></div><span className={`grid size-6 place-items-center rounded-full border ${checked ? "border-acid bg-acid text-black" : "border-white/15"}`}>{checked && <Check className="size-3.5" />}</span></button>;
}
