-- Classic Step 1B additive catalog refresh. Apply after committed 014–016.
-- Exact prior line/direction copy and UUIDs remain available to historical references.
-- Re-running does not republish moderated/archived rows. No score or media changes.
-- BEGIN CLASSIC V3 CATALOG
insert into public.content_packs (
  slug, name, eyebrow, description, access, state, categories,
  color, accent, icon, cover_tone, sort_order, featured, draw_enabled
) values
  ('internet-originals','Public Apology','Main character damage','Confessions, delusions, and apologies that somehow make it worse.','free','published',array['main-character'],'#D7FF3F','#121116','spark','internet-originals',10,true,true),
  ('stream-gremlins','Clip That','Chat has the receipts','Stream meltdowns, familiar phrases, and microphones that were definitely on.','free','published',array['streamer-mode'],'#A87CFF','#121116','live','stream-gremlins',20,true,true),
  ('gaming-comms','Skill Issue','Your team heard that','Failed clutches, hostile tutorials, and excuses with zero evidence.','free','published',array['gaming'],'#69F0AE','#121116','controller','gaming-comms',30,false,true),
  ('group-chat-evidence','Do Not Forward','The voice note stays here','Private confessions and social disasters with no plausible deniability.','free','published',array['group-chat'],'#FFB84D','#121116','bubble','group-chat-evidence',40,true,true),
  ('romance-rejection','Down Catastrophic','Read. Regret. Repeat.','Flirting, bad dates, and dignity left on read.','rotating','published',array['romance'],'#FF78C8','#121116','heart-crack','romance-rejection',50,false,true),
  ('impossible-energy','Final Boss Behavior','Pro: emotional whiplash','Grand declarations for people who absolutely cannot back them up.','pro','published',array['wildcard'],'#FF7448','#121116','warning','impossible-energy',60,false,true)
on conflict (slug) do update set
  name = excluded.name, eyebrow = excluded.eyebrow, description = excluded.description,
  color = excluded.color, accent = excluded.accent, icon = excluded.icon,
  cover_tone = excluded.cover_tone, sort_order = excluded.sort_order,
  featured = excluded.featured;

insert into public.energy_modifiers (slug, instruction, short_label, intensity, tags, state, draw_enabled)
values
  ('v2-confidence-tears','Sound outrageously confident while holding back tears; let one word wobble, then recover.','Winning. Barely.',4,array['confident','strained','contrast'],'published',true),
  ('v2-polite-fury','Whisper a furious outburst with immaculate politeness. Keep every word audible.','Whispered fury',3,array['quiet','whisper','angry'],'published',true),
  ('v2-sincere-confession','Confess with total sincerity, as if this is the bravest thing you have ever admitted.','Painfully sincere',2,array['quiet','sincere','confessional'],'published',true),
  ('v2-deadpan-evidence','Give flat, precise testimony. Pause before the most embarrassing detail; do not wink at the joke.','Under oath',1,array['quiet','deadpan','timing'],'published',true),
  ('v2-apology-smile','Start with a soft apology; become audibly proud halfway through, then pretend you did not.','Sorry you noticed',3,array['apology','contrast'],'published',true),
  ('v3-hold-laugh','Try not to laugh. Let one breath escape, then force the ending back into rigid seriousness.','Absolutely serious',3,array['restrained','comedy','multi-beat'],'published',true),
  ('v3-last-voicemail','Leave a voicemail pretending everything is fine. Let the final few words give away how badly you need a call back.','Please call back',3,array['confessional','escalating','multi-beat'],'published',true),
  ('v3-press-conference','Answer a question you wish nobody had asked. Start defensive; finish congratulating yourself.','No further questions',4,array['defensive','confident','multi-beat'],'published',true),
  ('v3-soft-threat','Use a warm, gentle voice. Let the final phrase turn cold, as if your patience has just run out.','Sweet little threat',2,array['quiet','controlled','villain','multi-beat'],'published',true),
  ('v2-fake-ad','Pitch every word like an irresistible deal. Make the worst detail your big selling point.','Buy my disaster',4,array['sales','confident'],'published',true),
  ('v3-bedtime-catastrophe','Soothe someone back to sleep. Give the worst word the same gentle care as "sweet dreams."','Sleep tight',1,array['quiet','gentle'],'published',true),
  ('v2-betrayed-teammate','Speak to your most trusted teammate after a betrayal. Hurt first; outrage at the end.','You promised',4,array['hurt','contrast'],'published',true),
  ('v2-no-breathless-rush','Start casually, realize everyone can hear you, and finish in tightly controlled panic.','Missed the mute',4,array['panic','contrast'],'published',true),
  ('v3-documentary-scandal','Describe this behavior with hushed scientific wonder. Sound grateful you lived long enough to witness it.','Rare behavior',2,array['quiet','wonder'],'published',true),
  ('v2-villain-crack','Begin with smooth villain menace, accidentally sound needy, then claw back your authority.','Evil. Mostly.',4,array['villain','contrast'],'published',true),
  ('v2-forbidden-whisper','Whisper an urgent secret to someone beside you. Be intense without raising your volume.','Do not wake them',2,array['quiet','whisper','urgent'],'published',true),
  ('v2-one-word-break','Keep a completely level voice until one important word; crack emotionally there, then go flat again.','The word that broke you',3,array['quiet','deadpan','contrast'],'published',true),
  ('v3-fake-casual','Try painfully hard to sound casual. Add a tiny nervous laugh, then pretend you never made it.','Obviously casual',2,array['awkward','restrained','multi-beat'],'published',true),
  ('v3-sports-final','Call the final seconds of a championship. Tighten the pace, pause before the ending, then release the suspense.','Last seconds',5,array['broadcast','escalating','multi-beat'],'published',true),
  ('v2-reverse-meltdown','Begin on the edge of a meltdown. Force your voice back into calm by the last few words.','Get it together',4,array['contrast','controlled'],'published',true),
  ('v2-no-context-pride','Accept an award for this exact behavior. Sound moved, grateful, and completely unashamed.','Standing ovation',3,array['proud','sincere'],'published',true),
  ('v2-quiet-winner','Speak softly and slowly, with the certainty of someone who has already won. No raised voice.','Already won',1,array['quiet','confident'],'published',true),
  ('v3-horror-realization','Begin with an ordinary observation. Pause as the meaning sinks in; finish in a clear, horrified whisper.','Oh. Oh no.',3,array['quiet','eerie','contrast'],'published',true),
  ('v3-news-desk','Read the news with crisp professionalism. Let a laugh threaten one word, swallow it, and keep broadcasting.','Keep broadcasting',3,array['broadcast','restrained','multi-beat'],'published',true),
  ('v2-romantic-disaster','Make it a tender declaration of love. Commit especially hard to the least romantic word.','This is love',2,array['gentle','romance'],'published',true),
  ('v2-wrong-room','Start with bold authority. Realize halfway through you are in the wrong room; finish anyway.','Wrong audience',4,array['awkward','contrast'],'published',true),
  ('v2-tiny-argument','Try to sound reasonable while clearly losing an argument. Stress the detail nobody believes.','Losing the argument',3,array['defensive','timing'],'published',true),
  ('v2-hero-last-stand','Deliver a wounded hero’s final request. Keep the words clear and make the ending absurdly noble.','One last request',4,array['dramatic','strained'],'published',true),
  ('v2-smug-explanation','Explain it with unbearable smugness. Treat the final detail as proof of your genius.','As I predicted',3,array['confident','comedy'],'published',true),
  ('v2-terrible-good-news','Announce it as wonderful news. Let doubt flash through once, then double down on the celebration.','Great news, somehow',4,array['victorious','contrast'],'published',true),
  ('v2-voice-assistant','Use a smooth automated voice that briefly glitches into real embarrassment, then resets.','Human mode failed',3,array['robotic','contrast'],'published',true),
  ('v3-bad-interrogation','Sound calmly innocent. Rush the detail that could incriminate you, then slow down far too much.','You cannot prove it',3,array['nervous','timing','multi-beat'],'published',true),
  ('v2-angry-gratitude','Sound intensely grateful through clenched frustration. Make the courtesy unmistakable.','Thank you so much',3,array['polite','angry'],'published',true),
  ('v3-manual-serious','Read this as a vital instruction from an appliance manual. Give one absurd word painfully precise emphasis.','Read the manual',2,array['quiet','deadpan','timing'],'published',true),
  ('v2-awe-to-disgust','Start in genuine wonder. Gradually realize this is disgusting; finish with defeated acceptance.','What a miracle',4,array['contrast','disgust'],'published',true),
  ('v2-tiny-emergency','Brief someone on a crisis in a low, steady voice. Put urgency into the pace, not the volume.','Controlled emergency',2,array['quiet','controlled','urgent'],'published',true)
on conflict (slug) do nothing;

with prompt_seed(pack_slug, category, difficulty, rating, scoring_focus, slug, body, tags, metadata) as (
  values
    ('internet-originals','main-character',1,'everyone',array['commitment','accuracy'],'v2-favorite-child','I am my own emergency contact. We are both panicking.',array['main-character','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','accuracy'],'v3-two-phone-calls','I faked a phone call to avoid someone. My phone rang. I answered both.',array['main-character','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','accuracy'],'v2-mirror-argument','I won an argument in the shower. I have called a press conference.',array['main-character','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','accuracy'],'v3-camera-relationship','I waved at a security camera. The guard waved back. I have to go there every day now.',array['main-character','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'teen',array['commitment','accuracy'],'v2-fake-account','I made a fake account to defend myself. It got bullied into agreeing with them.',array['main-character','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'teen',array['commitment','accuracy'],'v2-villain-budget','I cannot afford a villain era. I have to be a problem on public transport.',array['main-character','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'teen',array['commitment','accuracy'],'v2-crying-hot','I checked the mirror while crying. The sadness can wait. I look incredible.',array['main-character','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','accuracy'],'v2-apology-sponsor','This apology is sponsored by the consequences of my own bullshit.',array['main-character','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','accuracy'],'v2-emotional-support-lie','I faked a British accent on a first date. We have been married six fucking years.',array['main-character','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','accuracy'],'v2-blocked-therapist','I blocked my therapist. She kept bringing up things I specifically paid her to hear.',array['main-character','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','accuracy'],'v3-banned-list','I told the bouncer I was on the list. It was the fucking banned list.',array['main-character','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','accuracy'],'v2-character-witness','I asked for a character witness. My best friend said, "For the prosecution?" Fuck.',array['main-character','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','accuracy'],'v2-muted-scream','I have been screaming on mute for six minutes. The neighbors got the exclusive.',array['streamer-mode','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','accuracy'],'v2-chat-dad','Chat, stop calling him Dad. He is here to fix the internet.',array['streamer-mode','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','accuracy'],'v3-skip-how-to-move','I clicked "skip tutorial" and immediately searched "how to move."',array['streamer-mode','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','accuracy'],'v2-sponsor-mom','My mom asked what I do for work. I showed her the clip. She said, "Besides that."',array['streamer-mode','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'teen',array['commitment','accuracy'],'v2-clip-grandma','Who sent that clip to my grandma? She has started saying it at church.',array['streamer-mode','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'teen',array['commitment','accuracy'],'v2-stream-snore','I fell asleep on stream and gained viewers. The audience has made its position clear.',array['streamer-mode','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'teen',array['commitment','accuracy'],'v2-ban-me','Mods, ban me before I finish this sentence.',array['streamer-mode','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','accuracy'],'v3-dentist-breedable','Mute me. Mute me. Why is my dentist asking what "breedable" means?',array['streamer-mode','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','accuracy'],'v3-sponsored-breakup','This breakup is sponsored. Use code ABANDONED for ten percent off my fucking mattress.',array['streamer-mode','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','accuracy'],'v2-donation-confession','Thank you for the five dollars. I am not reading that fucking confession out loud.',array['streamer-mode','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','accuracy'],'v2-clutch-camera','I turned the camera off to lock in. I was naked from the waist down and losing.',array['streamer-mode','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','accuracy'],'v3-robot-sext','The donation robot just read my sext. It pronounced every fucking emoji.',array['streamer-mode','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','accuracy'],'v2-loot-goblin','I did not abandon the team. I heard a chest.',array['gaming','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','accuracy'],'v2-friendly-fire','The enemy team invited me back. They said I helped more than their fifth player.',array['gaming','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','accuracy'],'v2-boss-second-phase','The boss has a second phase. I have a bedtime.',array['gaming','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','accuracy'],'v3-bot-custody','The practice bot sent me a friend request. I think it wants custody.',array['gaming','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'teen',array['commitment','accuracy'],'v2-voice-crack','I said "watch this" and my voice cracked before my character died.',array['gaming','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'teen',array['commitment','accuracy'],'v2-ranked-breathing','Stop breathing into the mic. I cannot hear myself making excuses.',array['gaming','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'teen',array['commitment','accuracy'],'v3-single-player-lag','I blamed lag in a single-player game. Please let me finish lying.',array['gaming','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','accuracy'],'v2-ranked-flirting','I said "get fucked" to the boss. My date thought I was talking to them.',array['gaming','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','accuracy'],'v2-healer-payment','I am the healer. Say please or die with your fucking principles.',array['gaming','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','accuracy'],'v2-skill-funeral','I uninstalled out of respect for the people who made this shit.',array['gaming','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','accuracy'],'v2-fall-damage','I survived the apocalypse and died walking down some fucking stairs.',array['gaming','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','accuracy'],'v2-push-to-talk','I used push-to-talk to fart. I need to leave this server and start a new life.',array['gaming','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','accuracy'],'v2-voice-note-podcast','That was not a voice note. That was a hostage situation with chapters.',array['group-chat','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','accuracy'],'v3-photo-audit','I liked their old photo, panicked, and liked twelve more. It is an audit now.',array['group-chat','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','accuracy'],'v2-reply-everyone','I said "you too" when the dentist said "open wide." Neither of us recovered.',array['group-chat','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','accuracy'],'v3-birthday-without-me','I made a group chat for my birthday. They started planning without me.',array['group-chat','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'teen',array['commitment','accuracy'],'v3-screenshot-option-two','I sent them the screenshot of me asking how to reply to them. They said "option two."',array['group-chat','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'teen',array['commitment','accuracy'],'v2-typing-hostage','I have been typing for eleven minutes. The message is "okay."',array['group-chat','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'teen',array['commitment','accuracy'],'v3-full-name-sound-effect','Do not play that voice note out loud. I used your full name in the sound effect.',array['group-chat','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','accuracy'],'v2-toilet-unmute','I unmuted to flush so they would know I was done with this conversation.',array['group-chat','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','accuracy'],'v3-subpoena-award','If this chat gets subpoenaed, I was hacked. If it wins an award, I wrote the dick joke.',array['group-chat','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','accuracy'],'v2-nude-printer','I tried to send a nude and accidentally selected the printer. Dad is downstairs.',array['group-chat','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','accuracy'],'v2-poop-authorship','Someone used my bathroom and left a crime scene. I live alone.',array['group-chat','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','accuracy'],'v2-autocorrect-funeral','Autocorrect changed "condolences" to "congratulations." I sent a fucking balloon.',array['group-chat','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','accuracy'],'v2-date-handshake','They leaned in for a kiss. I panicked and said my full legal name.',array['romance','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','accuracy'],'v2-crush-door','I held the door for my crush and bowed. I do not know why I bowed.',array['romance','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','accuracy'],'v3-drive-through-rehearsal','I rehearsed asking them out. They heard me through the drive-through speaker.',array['romance','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','accuracy'],'v3-thumb-alibi','I watched their story in three seconds. My thumb needs an alibi.',array['romance','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'teen',array['commitment','accuracy'],'v3-no-pressure-question-marks','I said "no pressure" and sent three question marks. Separately.',array['romance','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'teen',array['commitment','accuracy'],'v2-read-receipt-romance','They left me on read. At least we are doing an activity together.',array['romance','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'teen',array['commitment','accuracy'],'v3-fix-me-estimate','They said they could fix me. I asked for an estimate.',array['romance','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','accuracy'],'v3-dirty-service-voice','Talk dirty to me. Actually, wait. Why are you using your customer service voice?',array['romance','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','accuracy'],'v3-casual-wife','We are keeping it casual. I have met his wife.',array['romance','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','accuracy'],'v3-own-name','I tried to moan their name and said my own. Honestly? Best sex of my life.',array['romance','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','accuracy'],'v2-booty-call-carpool','It was a booty call. I brought snacks and asked if anyone needed a ride home.',array['romance','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','accuracy'],'v2-date-safe-word','Our safe word is "commitment." Apparently I said it too early.',array['romance','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'everyone',array['commitment','accuracy'],'v2-final-boss-refund','I have come to collect what I am owed. It is seven dollars and you know it.',array['wildcard','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'everyone',array['commitment','accuracy'],'v2-royal-laundry','I called an emergency family meeting. Nobody is allowed to ask why my eyebrows are missing.',array['wildcard','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'everyone',array['commitment','accuracy'],'v3-door-single-combat','I challenged the automatic door to single combat. It only opens when I retreat.',array['wildcard','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'everyone',array['commitment','accuracy'],'v2-evil-laugh','I tried to leave dramatically. The door said pull. I gave it everything.',array['wildcard','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'teen',array['commitment','accuracy'],'v3-enemy-has-map','I followed my enemy to confront him. We are both lost. He has the map.',array['wildcard','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'teen',array['commitment','accuracy'],'v3-hold-my-hand','Hold my glasses. And my hand. This is escalating faster than I rehearsed.',array['wildcard','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'teen',array['commitment','accuracy'],'v2-power-pose','I practiced my entrance in the elevator. Someone was already in it.',array['wildcard','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'mature',array['commitment','accuracy'],'v3-devil-bank-balance','I told the devil he could not afford me. He showed me my fucking bank balance.',array['wildcard','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'mature',array['commitment','accuracy'],'v2-throne-toilet','I said "fear me" and my stomach made a noise like a fucking haunted drain.',array['wildcard','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'mature',array['commitment','accuracy'],'v3-begging-ambulance','I dropped to my knees to beg. They cracked so loud she asked if I needed a fucking ambulance.',array['wildcard','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'mature',array['commitment','accuracy'],'v3-two-men-context','I told everyone I could take two men at once. Apparently the context was important.',array['wildcard','confession'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',4,'mature',array['commitment','accuracy'],'v2-death-speech','Tell my enemies I died standing. Edit out the bit where I fell into the fucking hedge.',array['wildcard','boast'],'{"catalogVersion":"classic-content-v3","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-this-is-fine','This is fine.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://gunshowcomic.com/648","originalSourceUrl":"https://gunshowcomic.com/648","speaker":"KC Green; dialogue in Gunshow''s On Fire comic","context":"A character calmly denies a room on fire; original comic published January 9, 2013.","wordingVerification":"Visually read the second panel on the creator''s original page on September 5, 2026. Exact three words; sentence case normalized.","recognitionEvidence":"Documented meme history traces circulation from 2013; audience recognition has not been tested in Delivery.","recognitionSourceUrl":"https://en.wikipedia.org/wiki/Gunshow_(webcomic)","publicationRationale":"Three commonplace words used as a new player''s spoken declaration. The comic, character, fire scene, design, and merchandise identity are not reproduced.","limitations":"Editorial publication assessment, not legal clearance. Art and character rights remain outside this decision.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-immeasurable-disappointment','My disappointment is immeasurable and my day is ruined.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/watch?v=5d5NJgO38AE&t=363s","originalSourceUrl":"https://www.youtube.com/watch?v=5d5NJgO38AE","speaker":"TheReportOfTheWeek / Reviewbrah","context":"Reaction in Popeyes Cheddar Biscuit Butterfly Shrimp - Food Review, July 4, 2017.","wordingVerification":"Original upload''s English transcript at 6:03; export identifies captions as authored or unspecified. Exact nine words; punctuation normalized.","recognitionEvidence":"Source-linked meme history documents reaction-image and text reuse in July-December 2017.","recognitionSourceUrl":"https://knowyourmeme.com/memes/my-disappointment-is-immeasurable-and-my-day-is-ruined","publicationRationale":"A short, self-contained disappointed declaration used for players'' different performances. No review footage, restaurant branding, portrait, or creator imitation. The ordinary statement supports this narrow text-use decision; length alone is not the rationale.","limitations":"Creator has sold related merchandise. This is not a merchandise/branding license, endorsement, or general clearance of longer passages; rights assessment remains jurisdiction-dependent.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-wednesday','It is Wednesday, my dudes.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/watch?v=du-TY1GUFGk","originalSourceUrl":"https://www.youtube.com/watch?v=du-TY1GUFGk","speaker":"Jimmy Here, performing an existing Wednesday meme","context":"Creator-owned upload on April 9, 2016 of his short Vine performance. The underlying frog-caption meme predates this upload.","wordingVerification":"Original creator upload''s auto-generated English transcript at 0:00 reads the exact five words. Comma and capitalization normalized; scream omitted.","recognitionEvidence":"Know Your Meme documents the 2014 Tumblr predecessor, Jimmy Here''s 2016 Vine, and more than 140 related Vine results as of March 2016.","recognitionSourceUrl":"https://knowyourmeme.com/memes/it-is-wednesday-my-dudes","publicationRationale":"A brief weekday announcement using ordinary language. Text-only performance excludes the costume, frog art, scream recording, and creator voice.","limitations":"Caption verification is not human listening. The linked YouTube upload is an authenticated creator copy, not the first publication of the meme or Vine.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-emotional-damage','Emotional damage!',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/watch?v=miD_TWmdGIY&t=66s","originalSourceUrl":"https://www.youtube.com/watch?v=miD_TWmdGIY","speaker":"Steven He","context":"Short reaction in his September 21, 2021 video-game comedy sketch.","wordingVerification":"The two words occur in the original upload''s auto-generated transcript at 1:06 and in Steven He''s own quoted explanation in YouTube''s January 10, 2024 interview.","recognitionEvidence":"In YouTube''s direct 2024 creator interview, He describes viewers repeating the phrase; this is qualitative creator testimony, not a recognition percentage.","recognitionSourceUrl":"https://blog.youtube/creator-and-artist-stories/steven-he-jeenie-weenie-collab/","publicationRationale":"Two common descriptive words. The player supplies an independent interpretation; no accent, ethnicity, character, imitation, soundbite, or targeted insult is part of the assignment.","limitations":"No use of the creator''s branded merchandise, persona, or audiovisual sketch is authorized by this text decision.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-chat-is-this-real','Chat, is this real?',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.urbandictionary.com/define.php?term=chat+is+this+real","originalSourceUrl":null,"speaker":"Distributed streamer/chat phrase; no single author asserted","context":"A streamer-style request for confirmation, often applied to obviously fake content.","wordingVerification":"Exact four-word question is attested in the source''s body and September 26, 2025 entry, with a June 3, 2023 ''yo'' variant. This is a documented idiom, not a verified quote from one iShowSpeed clip.","recognitionEvidence":"Know Your Meme''s June 7, 2023 entry traces streamer clips and cross-platform caption use in March-June 2023.","recognitionSourceUrl":"https://knowyourmeme.com/memes/chat-is-this-real","publicationRationale":"Ordinary question plus a generic audience address, used as distributed slang without assigning a creator or reproducing a clip.","limitations":"Earliest coinage is not established; the commonly cited iShowSpeed example only establishes one use of a related question. No 2026 popularity claim.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('gaming-comms','gaming',1,'teen',array['commitment','comedy','accuracy'],'v3-ref-bite-of-87','Was that the bite of ''87?!',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/watch?v=AZgnZSmbYn0&t=580s","originalSourceUrl":"https://www.youtube.com/watch?v=AZgnZSmbYn0","speaker":"Markiplier","context":"A surprised question while playing Five Nights at Freddy''s 4, Part 5, July 27, 2015. The question is not a claim about the game''s correct chronology.","wordingVerification":"Original upload''s auto-generated English transcript at 9:40: exact six words. Apostrophe and punctuation normalized.","recognitionEvidence":"The source-linked meme entry documents remixes and quotations associated with this reaction.","recognitionSourceUrl":"https://knowyourmeme.com/memes/was-that-the-bite-of-87","publicationRationale":"A short factual-style question referencing an event name; no game dialogue sequence, game artwork, character, clip audio, or voice imitation is reproduced.","limitations":"Spicy rating acknowledges horror/injury context. This does not license Five Nights at Freddy''s assets or imply Markiplier or game-owner endorsement; captions are not human listening.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-big-brain-time','Yeah, this is big brain time.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.wired.com/video/watch/markiplier-explores-his-impact-on-the-internet","originalSourceUrl":"https://www.youtube.com/watch?v=ByLrbLiSL6k","speaker":"Markiplier","context":"Boast recalled by Markiplier in WIRED''s December 18, 2019 direct interview; earlier gameplay source is Baldi''s Basics 1 Year Birthday Bash.","wordingVerification":"Exact six-word contiguous excerpt of the creator''s spoken recollection in WIRED''s published interview transcript. His preceding ''Oh'' is outside the selected excerpt. The original gameplay transcript was unavailable; not verified from its title.","recognitionEvidence":"WIRED''s interview explicitly discusses the phrase as a meme and Markiplier describes its spread. This is contemporary 2019 primary testimony.","recognitionSourceUrl":"https://www.wired.com/video/watch/markiplier-explores-his-impact-on-the-internet","publicationRationale":"Brief colloquial boast, without the edited head image, game visuals, or creator voice. Only the commonplace short expression is used.","limitations":"Source verifies the 2019 interview wording, not the first gameplay utterance. No claim that a source title verified speech or that the creator endorses Delivery.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-let-him-cook','Let him cook.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.dictionary.com/culture/slang/let-him-cook","originalSourceUrl":null,"attestationUrl":"https://twitter.com/MrSmith120/status/27481570231","speaker":"Distributed slang; early use documented in Lil B fan culture","context":"Let someone continue an attempt, sincerely or with terrible confidence. Related ''let that boy cook'' wording appears in Lil B posts in 2010.","wordingVerification":"Exact three-word phrase in the dictionary''s body and embedded October 15, 2010 post. Direct historical Twitter fetch failed; not attributed as Lil B''s exact personal quote or first coinage.","recognitionEvidence":"Dictionary.com, November 7, 2023, records use across music fandom, sports, and memes with dated examples.","recognitionSourceUrl":"https://www.dictionary.com/culture/slang/let-him-cook","publicationRationale":"An ordinary three-word imperative now used as an idiom. No lyrics, music, dance, branded image, or attributed invented quote.","limitations":"Original coinage remains uncertain; the historical post is an attestation lead, not proof of authorship. Dictionary wording, not its definition, is the playable text.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-touch-grass','Touch grass.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://dictionary.cambridge.org/dictionary/english/touch-grass","originalSourceUrl":null,"speaker":"Distributed internet idiom; no individual credited","context":"A request to step away from the internet and return to the physical world.","wordingVerification":"Exact two-word idiom in Cambridge''s entry and usage examples; this is text attestation, not a creator clip quote.","recognitionEvidence":"Cambridge and Dictionary.com include the idiom; the latter dates first recording to 2015-20 and includes dated 2025-26 usage.","recognitionSourceUrl":"https://www.dictionary.com/browse/touch-grass","publicationRationale":"A two-word common imperative/idiom, without any copied definition, personal attribution, or identity asset.","limitations":"No earliest original post established. Lexicographic inclusion is evidence of use, not a measured recognition rate among players.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-weird-flex','Weird flex, but OK.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.dictionary.com/culture/slang/weird-flex-but-okay","originalSourceUrl":"https://twitter.com/SJSchauer/status/1044353823769268227","speaker":"Distributed internet response; prominent 2018 use by Sarah Schauer","context":"A baffled response to an unusual boast. The game does not target the people discussed in the historical tweets.","wordingVerification":"Exact four-word phrase and OK/okay variants in Dictionary.com''s entry body and embedded dated posts. Punctuation normalized; selected as an idiom, not a verbatim quote from the linked ''okay'' tweet.","recognitionEvidence":"Dictionary.com published its entry November 21, 2018 and records spread during 2018; Cambridge also includes it under flex.","recognitionSourceUrl":"https://www.dictionary.com/culture/slang/weird-flex-but-okay","publicationRationale":"Short conversational response built from common slang. No copying the longer social-media jokes, targets, avatars, or product branding.","limitations":"The linked post is a popularization source, not original coinage or exact spelling of the selected variant. Historical post access may fail.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-head-empty','No thoughts, head empty.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.tumblr.com/fantastic-nonsense/673568579625582592/no-thoughts-head-empty-just-remembering-wally","originalSourceUrl":null,"attestationUrl":"https://twitter.com/spruiko/status/965877427577630720","speaker":"Distributed internet caption; no creator quotation asserted","context":"A self-directed declaration of having nothing useful to say, useful for a painfully sincere or overconfident performance.","wordingVerification":"Exact four-word sequence appears in the readable body of the linked Tumblr user''s post. The reported February 20, 2018 source tweet returns 404; no first-author claim.","recognitionEvidence":"Know Your Meme''s May 20, 2020 entry documents 2018-19 caption variations and explicitly calls the origin unclear.","recognitionSourceUrl":"https://knowyourmeme.com/memes/no-thoughts-head-empty","publicationRationale":"Brief commonplace self-description used independently of the cartoon and game images associated with early captions. No attack on a named person or disability.","limitations":"The primary original post is unavailable. Published as an attested distributed phrase, not attributed to the Tumblr user as its inventor.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-i-like-turtles','I like turtles.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://shortyawards.com/16th/paramount-teenage-mutant-ninja-turtles-i-like-turtles","originalSourceUrl":null,"attestationUrl":"https://www.youtube.com/watch?v=CMNry4PE93Y","speaker":"Jonathon Ware","context":"An unexpected answer to a KGW interview at Portland''s Rose Festival in 2007; Ware reprised the phrase as an adult in 2023.","wordingVerification":"The producer''s first-person 2023 campaign case study explicitly transcribes the three-word spoken answer. The 2007 link is an archival upload by CaptJax458, not the broadcaster''s original account.","recognitionEvidence":"The 2023 campaign deliberately recreated the 2007 meme with Ware. Its award submission reports cross-platform response, which is self-reported promotional evidence, not an independent audience study.","recognitionSourceUrl":"https://shortyawards.com/16th/paramount-teenage-mutant-ninja-turtles-i-like-turtles","publicationRationale":"Three ordinary words expressing an animal preference. Player performance uses no child likeness, zombie makeup, broadcaster footage, movie characters, or endorsement; directions do not impersonate a child.","limitations":"The campaign''s agreement with Ware does not confer rights to Delivery. Publication rests on narrow ordinary-text use, not that agreement or the archival uploader''s authority.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('impossible-energy','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v3-ref-double-rainbow','Double rainbow all the way across the sky.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/watch?v=OQSNhk5ICTI&t=53s","originalSourceUrl":"https://www.youtube.com/watch?v=OQSNhk5ICTI","speaker":"Paul ''Bear'' Vasquez / Yosemitebear62","context":"Describing a rainbow outside his home in the original January 8, 2010 upload.","wordingVerification":"Exact eight-word contiguous excerpt in the original upload''s English transcript at 0:53. Captions labeled authored or unspecified. Preceding ''It''s full on'' is outside the excerpt.","recognitionEvidence":"YouTube''s December 12, 2010 year-end report placed the original sixth among its non-major-label most-watched videos as of November 2010.","recognitionSourceUrl":"https://blog.youtube/culture-and-trends/double-rainbows-annoying-oranges-and/","publicationRationale":"A short descriptive observation of a natural phenomenon. No creator audio, crying, scenery, song/remix lyrics beyond the prior spoken phrase, or identity asset is used.","limitations":"Caption verification is not human listening. The estate and music/remix rights are not licensed; only this ordinary spoken text excerpt is included.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb),
    ('impossible-energy','wildcard',1,'mature',array['commitment','comedy','accuracy'],'v3-ref-find-out','Fuck around and find out.',array['recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v3","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.suebutler.com.au/new-words/2026/1/12/fafo","originalSourceUrl":null,"speaker":"Established vulgar idiom; no single speaker or origin claimed","context":"A warning about consequences, played as an absurd boast or restrained warning rather than a real threat toward anyone.","wordingVerification":"Exact five-word expansion in lexicographer Sue Butler''s January 12, 2026 entry and in Wiktionary''s phrase entry.","recognitionEvidence":"The dated lexicographer commentary treats the expression as established US colloquial language and discusses its acronym. That is attestation, not proof of 2026 popularity.","recognitionSourceUrl":"https://www.suebutler.com.au/new-words/2026/1/12/fafo","publicationRationale":"Common vulgar idiom with no creator attribution, quoted speech, logo, political endorsement, or copied explanatory text. Mature opt-in is required.","limitations":"Earliest coinage is disputed. Do not attach political imagery, a named target, or authentic-threat context to this performance assignment.","publicationDecision":"publish-text-only","reviewedAt":"2026-09-05"}}'::jsonb)
), upserted as (
  insert into public.prompts (slug, body, category, difficulty, rating, scoring_focus, tags, locale, state, source, draw_enabled, metadata)
  select slug, body, category, difficulty::smallint, rating::public.content_rating, scoring_focus, tags, 'en', 'published', 'built_in', true, metadata
  from prompt_seed
  on conflict (slug) do nothing
  returning id, slug
), canonical as (
  select id, slug from upserted
  union all
  select p.id, p.slug from public.prompts p join prompt_seed seed on seed.slug = p.slug
)
insert into public.pack_prompts (pack_id, prompt_id, sort_order)
select pack.id, prompt.id, row_number() over (partition by seed.pack_slug order by seed.slug)::integer
from prompt_seed seed
join canonical prompt on prompt.slug = seed.slug
join public.content_packs pack on pack.slug = seed.pack_slug
on conflict (pack_id, prompt_id) do nothing;

-- Retire only replaced Step 1 identities; old body/state/history joins are unchanged.
update public.prompts set draw_enabled = false where slug in (
  'v2-apology-draft', 'v2-wrong-door', 'v2-god-favorites', 'v2-tutorial-betrayal', 'v2-open-mic', 'v2-sponsor-candle', 'v2-chat-receipts', 'v2-training-dummy', 'v2-controller-alibi', 'v2-accidental-like', 'v2-birthday-investigation', 'v2-screenshot-spiral', 'v2-voice-note-laugh', 'v2-group-chat-court', 'v2-date-bread', 'v2-crush-story', 'v2-date-split', 'v2-hot-red-flag', 'v2-dirty-talk-weather', 'v2-situationship-app', 'v2-sexy-voice', 'v2-destiny-password', 'v2-revenge-calendar', 'v2-fear-chihuahua', 'v2-god-receipt', 'v2-knees-cracked', 'v2-demons-rent'
);
update public.energy_modifiers set draw_enabled = false where slug in (
  'v2-hold-laugh', 'v2-last-voicemail', 'v2-press-conference-v2', 'v2-soft-threat', 'v2-bedtime-catastrophe', 'v2-documentary-scandal', 'v2-fake-casual', 'v2-sports-final', 'v2-horror-realization', 'v2-news-desk', 'v2-bad-interrogation', 'v2-delayed-laugh'
);
-- END CLASSIC V3 CATALOG

-- Preserve existing canonical Daily slots; newly generated dates are clean.
create or replace function public.ensure_daily_challenge(p_date date, p_market text default 'global')
returns public.daily_challenges
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_prompt uuid;
  selected_difficulty smallint;
  selected_body text;
  selected_energy uuid;
  result public.daily_challenges;
  normalized_market text := lower(coalesce(nullif(btrim(p_market), ''), 'global'));
  day_start timestamptz := (p_date::timestamp at time zone 'UTC');
begin
  if p_date is null then
    raise exception using errcode = '22023', message = 'A Daily challenge date is required';
  end if;

  -- Existing canonical dates win before catalog availability is considered.
  select * into result from public.daily_challenges
  where challenge_date = p_date and market = normalized_market;
  if found then return result; end if;

  select p.id, p.difficulty, p.body into selected_prompt, selected_difficulty, selected_body
  from public.prompts p
  where p.state = 'published'
    and p.draw_enabled and p.rating = 'everyone'::public.content_rating
    and (p.available_from is null or p.available_from <= day_start)
    and (p.available_until is null or p.available_until > day_start)
    and exists (
      select 1
      from public.pack_prompts pp
      join public.content_packs pack on pack.id = pp.pack_id
      where pp.prompt_id = p.id
        and pack.state = 'published' and pack.draw_enabled
        and pack.access in ('free', 'rotating')
        and (pack.available_from is null or pack.available_from <= day_start)
        and (pack.available_until is null or pack.available_until > day_start)
    )
  order by md5(p_date::text || ':' || normalized_market || ':prompt:' || p.id::text)
  limit 1;

  select id into selected_energy
  from public.energy_modifiers
  where state = 'published' and draw_enabled
    and (not (tags && array['contrast', 'multi-beat']::text[]) or cardinality(regexp_split_to_array(btrim(selected_body), '\s+')) >= 8)
    and (
      compatible_difficulties is null
      or selected_difficulty = any(compatible_difficulties)
    )
  order by md5(p_date::text || ':' || normalized_market || ':energy:' || id::text)
  limit 1;

  if selected_prompt is null or selected_energy is null then
    raise exception 'Published prompt and energy content must exist before generating a daily challenge';
  end if;

  insert into public.daily_challenges (challenge_date, market, prompt_id, energy_modifier_id)
  values (p_date, normalized_market, selected_prompt, selected_energy)
  on conflict (challenge_date, market) do nothing;

  select * into result from public.daily_challenges
  where challenge_date = p_date and market = normalized_market;
  return result;
end;
$$;

