-- September content drop. Additive only: previous copy, IDs, ratings, and moderation stay intact.
-- BEGIN CLASSIC V4 CATALOG
insert into public.content_packs (
  slug, name, eyebrow, description, access, state, categories,
  color, accent, icon, cover_tone, sort_order, featured, draw_enabled
) values
  ('can-you-hear-me','Can You Hear Me?','Still on the call','Meetings, customer service, and being professional against your will.','free','published',array['workplace','customer-service'],'#5d7cff','#070707','bubble','can-you-hear-me',70,true,true),
  ('ordinary-emergency','Ordinary Emergency','Somebody get a towel','Roommates, family dinners, and problems that did not need to escalate.','free','published',array['wildcard','group-chat'],'#ff7a2f','#070707','warning','ordinary-emergency',80,true,true)
on conflict (slug) do update set
  name = excluded.name, eyebrow = excluded.eyebrow, description = excluded.description,
  color = excluded.color, accent = excluded.accent, icon = excluded.icon,
  cover_tone = excluded.cover_tone, sort_order = excluded.sort_order,
  featured = excluded.featured;

with prompt_seed(pack_slug, category, difficulty, rating, scoring_focus, slug, body, tags, metadata) as (
  values
    ('internet-originals','main-character',1,'everyone',array['commitment','comedy','accuracy'],'v4-ref-literally','Literally.',array['main-character','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/watch?v=7DXsGpHoolY","creator":"PurpleStars02","verification":"Single-word acting-challenge prompt identified in the primary upload during the September 7 research.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','comedy','accuracy'],'v4-apology-sequel','Before I apologize, which part did you hear?',array['main-character','apology'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','comedy','accuracy'],'v4-chair-presentation','Please stop spinning my chair. I am trying to look important.',array['main-character','authority'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'everyone',array['commitment','comedy','accuracy'],'v4-dramatic-exit-bag','Can somebody bring my bag? I already did the dramatic exit.',array['main-character','awkward'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'teen',array['commitment','comedy','accuracy'],'v4-apology-lighting','I will take accountability as soon as we fix this lighting.',array['main-character','apology'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'teen',array['commitment','comedy','accuracy'],'v4-terrible-third-option','There were two good choices. I made a third one.',array['main-character','confession'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','comedy','accuracy'],'v4-apology-comments','I said I was sorry. Why the fuck are you agreeing with the comments?',array['main-character','apology'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',1,'mature',array['commitment','comedy','accuracy'],'v4-calm-footage','I was extremely calm until you showed me the fucking footage.',array['main-character','denial'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','comedy','accuracy'],'v4-humble-bastard','I am trying to be humble, but these bastards keep being wrong.',array['main-character','boast'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('internet-originals','main-character',2,'mature',array['commitment','comedy','accuracy'],'v4-personal-growth-spite','This is personal growth. I used to do this shit for free.',array['main-character','boast'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','comedy','accuracy'],'v4-ref-absolute-air','Absolute air mate.',array['streamer-mode','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.instagram.com/reel/Dc4ACLksPVx/","creator":"Mia Mendes","verification":"Phrase confirmed on screen during the September 7 research; punctuation normalized.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'everyone',array['commitment','comedy','accuracy'],'v4-chat-doorbell','Chat, that was the doorbell. Nobody donated a person.',array['streamer-mode','chat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'everyone',array['commitment','comedy','accuracy'],'v4-chat-one-job','Your one job was to act normal while my mom was here.',array['streamer-mode','chat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'everyone',array['commitment','comedy','accuracy'],'v4-clip-the-comeback','Can we clip the comeback? I have not done it yet, but stay ready.',array['streamer-mode','stream'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'teen',array['commitment','comedy','accuracy'],'v4-mod-family','Who gave my dad moderator? He is grounding people.',array['streamer-mode','chat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'teen',array['commitment','comedy','accuracy'],'v4-chat-fact-check','Stop fact-checking me. We are trying to have a moment.',array['streamer-mode','chat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'mature',array['commitment','comedy','accuracy'],'v4-sponsor-shirt','Do not show the sponsor my fucking shirt. Turn me around.',array['streamer-mode','stream'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',1,'mature',array['commitment','comedy','accuracy'],'v4-chat-daddy','I said the character was cool. Who the fuck typed daddy?',array['streamer-mode','innuendo'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','comedy','accuracy'],'v4-clip-evidence','Delete that clip. I was a different person forty fucking seconds ago.',array['streamer-mode','panic'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('stream-gremlins','streamer-mode',2,'mature',array['commitment','comedy','accuracy'],'v4-hot-mic-finish','The mic was on? Which part of the sentence about my ass?',array['streamer-mode','hot-mic'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'mature',array['commitment','comedy','accuracy'],'v4-ref-surprise','Surprise motherfucker!',array['gaming','dubbing-reference','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.instagram.com/reel/DcEDYbliMyS/","creator":"Baz; dubbing a Dexter scene","verification":"Indexed transcript reads Surprise Mothafucka; spelling normalized. Text only, no scene or voice included.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('gaming-comms','gaming',2,'everyone',array['commitment','comedy','accuracy'],'v4-healer-decorating','I thought you were healing me. Why are you decorating the house?',array['gaming','teammate'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','comedy','accuracy'],'v4-clutch-witnesses','Everybody look away. I play better without witnesses.',array['gaming','clutch'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','comedy','accuracy'],'v4-enemy-polite','The enemy said nice try. That felt worse.',array['gaming','defeat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'everyone',array['commitment','comedy','accuracy'],'v4-crouch-negotiation','Stop shooting. I am trying to communicate by crouching.',array['gaming','teammate'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'teen',array['commitment','comedy','accuracy'],'v4-settings-accountability','Give me a minute. There has to be a setting that makes this your fault.',array['gaming','excuse'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'teen',array['commitment','comedy','accuracy'],'v4-tutorial-judge','Even the tutorial paused to watch me fail.',array['gaming','defeat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',1,'mature',array['commitment','comedy','accuracy'],'v4-grenade-ownership','Whose fucking grenade is that? Oh. Mine. Everybody run.',array['gaming','panic'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','comedy','accuracy'],'v4-boss-shoe','I spent an hour building this character and died to a big fucking shoe.',array['gaming','defeat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('gaming-comms','gaming',2,'mature',array['commitment','comedy','accuracy'],'v4-enemy-dinner','You can talk shit after the match. Right now I need you to revive me.',array['gaming','teammate'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'mature',array['commitment','comedy','accuracy'],'v4-ref-shut-up','Shut the fuck up.',array['group-chat','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.instagram.com/reel/DZUgiwyseVF/","creator":"Mia Mendes","verification":"On-screen prompt abbreviates the profanity; indexed speech provides the expanded wording used here.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','comedy','accuracy'],'v4-ref-second','Give me a second.',array['group-chat','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.snapchat.com/@nessa20252624/spotlight/W7_EDlXWTBiXAEEniNoMPwAAYcGZlc2p5eXlwAZ806lU-AZ806jheAAAAAQ","creator":"nessa20252624; source attestation, not claimed original creator","verification":"Brief acting-challenge phrase attested in the September 7 research; no complete performance is reproduced.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('group-chat-evidence','group-chat',1,'everyone',array['commitment','comedy','accuracy'],'v4-screenshot-sequel','Why is there a second screenshot? I explained the first one.',array['group-chat','receipts'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'everyone',array['commitment','comedy','accuracy'],'v4-typing-committee','Please stop helping me flirt. There are six people typing this message.',array['group-chat','group-chat'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'everyone',array['commitment','comedy','accuracy'],'v4-voice-note-arrival','Before you play that voice note, tell me who is in the car.',array['group-chat','voice-note'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'teen',array['commitment','comedy','accuracy'],'v4-wrong-chat-linger','Wrong chat. Unless you agree. Then I meant to send it.',array['group-chat','awkward'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'teen',array['commitment','comedy','accuracy'],'v4-evidence-zoom','You can zoom in. It will not make the story better.',array['group-chat','receipts'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',1,'mature',array['commitment','comedy','accuracy'],'v4-airdrop-regret','Who the fuck accepts a random AirDrop at a family wedding?',array['group-chat','awkward'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','comedy','accuracy'],'v4-voice-note-advice','I asked for advice, not a fucking dramatic reading of my texts.',array['group-chat','voice-note'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('group-chat-evidence','group-chat',2,'mature',array['commitment','comedy','accuracy'],'v4-group-therapist','Please stop sending my therapist the memes. She already knows I am a mess.',array['group-chat','oversharing'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','comedy','accuracy'],'v4-ref-missed-you','I missed you.',array['romance','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.facebook.com/PurpleStars02Official/videos/emoji-acting-challenge-challenge-acting-viral-funny-trending/932513232876529/","creator":"PurpleStars02","verification":"Short repeated phrase in the creator''s indexed acting-challenge transcript; punctuation normalized.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('romance-rejection','romance',2,'everyone',array['commitment','comedy','accuracy'],'v4-date-gps','You have beautiful eyes. Sorry, I was supposed to say turn left.',array['romance','awkward'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'everyone',array['commitment','comedy','accuracy'],'v4-date-bread-insurance','If this goes badly, can we still order the garlic bread?',array['romance','dating'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'everyone',array['commitment','comedy','accuracy'],'v4-flirt-complaint','Was that flirting? I need to know before I file a complaint.',array['romance','flirting'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'teen',array['commitment','comedy','accuracy'],'v4-heart-receipt','You hearted the message and answered the question I did not ask.',array['romance','dating'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'teen',array['commitment','comedy','accuracy'],'v4-date-light-switch','I thought we had a spark. Turns out your lamp does that to everybody.',array['romance','rejection'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',1,'mature',array['commitment','comedy','accuracy'],'v4-dirty-talk-password','Talk dirty to me. Okay, that is my actual password. Stop.',array['romance','innuendo'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','comedy','accuracy'],'v4-choke-rent','I said choke me and you asked about my rent. That fucking worked.',array['romance','innuendo'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','comedy','accuracy'],'v4-walk-of-shame','This is a walk of shame. Why the fuck is the doorbell playing a fanfare?',array['romance','awkward'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('romance-rejection','romance',2,'mature',array['commitment','comedy','accuracy'],'v4-sexy-sock','I was trying to look sexy. My sock is stuck on your plant.',array['romance','innuendo'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-villain-hold-button','Your doom is inevitable. Please hold while I find the button.',array['wildcard','villain'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-prophecy-parking','The prophecy did not mention that parking would be this difficult.',array['wildcard','dramatic'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-pigeon-crown','The pigeon has taken my crown. We are negotiating.',array['wildcard','absurd'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-evil-lair-socks','Remove your shoes before entering my evil lair. I just mopped.',array['wildcard','villain'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',1,'teen',array['commitment','comedy','accuracy'],'v4-dramatic-cape','Do not step on the cape. I am making a threat.',array['wildcard','villain'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',2,'teen',array['commitment','comedy','accuracy'],'v4-tiny-council','I have assembled my council. One of them is a very small dog.',array['wildcard','absurd'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',2,'mature',array['commitment','comedy','accuracy'],'v4-haunted-sexy','The house is haunted, but the ghost has a stupidly sexy voice.',array['wildcard','innuendo'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',2,'mature',array['commitment','comedy','accuracy'],'v4-demon-landlord','I summoned a demon. It asked if the landlord knows about the fucking candles.',array['wildcard','absurd'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',2,'mature',array['commitment','comedy','accuracy'],'v4-villain-customer-support','I will destroy you. As soon as customer support fixes this bullshit.',array['wildcard','villain'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('impossible-energy','wildcard',2,'mature',array['commitment','comedy','accuracy'],'v4-raccoon-manners','There is a raccoon in my bathrobe. Do not be rude. He lives here now, asshole.',array['wildcard','absurd'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',1,'everyone',array['commitment','comedy','accuracy'],'v4-ref-tired','You look tired.',array['workplace','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.youtube.com/shorts/u5Iu3YVCGMI","creator":"Acting-challenge upload; no first-origin claim","verification":"Repeated short prompt identified in the September 7 research. No popularity ranking asserted.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('can-you-hear-me','workplace',2,'everyone',array['commitment','comedy','accuracy'],'v4-meeting-name','Can you say my name again? I was not ready to be involved.',array['workplace','meeting'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',1,'everyone',array['commitment','comedy','accuracy'],'v4-on-hold-harmony','Please put me back on hold. I was enjoying the song.',array['workplace','customer-service'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',2,'everyone',array['commitment','comedy','accuracy'],'v4-screen-share-desktop','That is my desktop. We will not be taking questions about the folders.',array['workplace','meeting'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',1,'teen',array['commitment','comedy','accuracy'],'v4-circle-back-exit','When you say circle back, how big can the circle be?',array['workplace','workplace'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',2,'teen',array['commitment','comedy','accuracy'],'v4-customer-service-name','I am happy to help. That is my customer service voice, not a promise.',array['workplace','customer-service'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',2,'mature',array['commitment','comedy','accuracy'],'v4-professional-unmute','I said what the fuck very professionally. Unfortunately, I was not muted.',array['workplace','hot-mic'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',2,'mature',array['commitment','comedy','accuracy'],'v4-reply-all-goodbye','If you reply all one more fucking time, I am coming to your desk.',array['workplace','workplace'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',1,'mature',array['commitment','comedy','accuracy'],'v4-printer-attitude','The printer has a paper jam and a shitty fucking attitude.',array['workplace','workplace'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('can-you-hear-me','workplace',1,'mature',array['commitment','comedy','accuracy'],'v4-corporate-plain-english','By interesting approach, I meant what the fuck are you doing?',array['workplace','customer-service'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-ref-grandma','Grandma stop.',array['wildcard','acting-challenge','recognizable','text-reference','short-line'],'{"catalogVersion":"classic-content-v4","publicationStatus":"short-text-editorial","recognitionSource":{"sourceUrl":"https://www.instagram.com/reel/DZhTcWXsB7q/","creator":"Mia Mendes","verification":"Phrase confirmed on screen during the September 7 research; punctuation normalized.","reviewedAt":"2026-09-07"}}'::jsonb),
    ('ordinary-emergency','wildcard',2,'everyone',array['commitment','comedy','accuracy'],'v4-fridge-eye-contact','Close the fridge. The cheese and I are having a private conversation.',array['wildcard','absurd'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-roommate-lid','Whatever you do, do not lift that lid with confidence.',array['wildcard','roommate'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',1,'everyone',array['commitment','comedy','accuracy'],'v4-doorbell-pajamas','Everybody stay quiet. I am wearing the embarrassing pajamas.',array['wildcard','everyday'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',1,'teen',array['commitment','comedy','accuracy'],'v4-family-dinner-evidence','Can we pass the potatoes before we discuss the evidence?',array['wildcard','family'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',2,'teen',array['commitment','comedy','accuracy'],'v4-spider-new-lease','The spider can keep the bathroom. I will brush my teeth outside.',array['wildcard','everyday'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',1,'mature',array['commitment','comedy','accuracy'],'v4-roomba-pants','Why is the fucking vacuum wearing my underwear?',array['wildcard','absurd'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',2,'mature',array['commitment','comedy','accuracy'],'v4-toilet-confidence','Nobody flush. I need everyone in this house to fucking believe in me.',array['wildcard','bathroom'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',2,'mature',array['commitment','comedy','accuracy'],'v4-dinner-innuendo','I said the sausage was impressive. Why are you making dinner weird?',array['wildcard','innuendo'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb),
    ('ordinary-emergency','wildcard',1,'mature',array['commitment','comedy','accuracy'],'v4-microwave-regret','Who microwaved fish? Show yourself, you smelly little bastard.',array['wildcard','roommate'],'{"catalogVersion":"classic-content-v4","publicationStatus":"original-editorial"}'::jsonb)
), upserted as (
  insert into public.prompts (slug, body, category, difficulty, rating, scoring_focus, tags, locale, state, source, draw_enabled, metadata)
  select slug, body, category, difficulty::smallint, rating::public.content_rating, scoring_focus, tags, 'en', 'published', 'built_in', true, metadata
  from prompt_seed
  on conflict (slug) do nothing
  returning id, slug
), canonical as (
  select id, slug from upserted
  union all
  select p.id, p.slug from public.prompts p join prompt_seed seed on seed.slug = p.slug
)
insert into public.pack_prompts (pack_id, prompt_id, sort_order)
select pack.id, prompt.id, 100 + row_number() over (partition by seed.pack_slug order by seed.slug)::integer
from prompt_seed seed
join canonical prompt on prompt.slug = seed.slug
join public.content_packs pack on pack.slug = seed.pack_slug
on conflict (pack_id, prompt_id) do nothing;
-- END CLASSIC V4 CATALOG
